"""init schema

Revision ID: ea747d0049a9
Revises: 
Create Date: 2025-08-24 18:09:03.389674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea747d0049a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auteur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('prenom', sa.String(length=255), nullable=True),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('editeur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emplacement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colonne', sa.Integer(), nullable=False),
    sa.Column('etage', sa.String(length=16), nullable=False),
    sa.Column('zone', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('langue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oeuvre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=512), nullable=False),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active_flag', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=512), nullable=False),
    sa.Column('editeur_id', sa.Integer(), nullable=True),
    sa.Column('langue_id', sa.Integer(), nullable=True),
    sa.Column('serie_id', sa.Integer(), nullable=True),
    sa.Column('numero_serie', sa.Integer(), nullable=True),
    sa.Column('emplacement_id', sa.Integer(), nullable=True),
    sa.Column('lien_couverture', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['editeur_id'], ['editeur.id'], ),
    sa.ForeignKeyConstraint(['emplacement_id'], ['emplacement.id'], ),
    sa.ForeignKeyConstraint(['langue_id'], ['langue.id'], ),
    sa.ForeignKeyConstraint(['serie_id'], ['serie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oeuvre_auteur',
    sa.Column('oeuvre_id', sa.Integer(), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['auteur.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['oeuvre_id'], ['oeuvre.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('oeuvre_id', 'auteur_id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('livre_auteur',
    sa.Column('livre_id', sa.Integer(), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['auteur.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['livre_id'], ['livres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('livre_id', 'auteur_id')
    )
    op.create_table('livre_genre',
    sa.Column('livre_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['livre_id'], ['livres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('livre_id', 'genre_id')
    )
    op.create_table('livre_oeuvre',
    sa.Column('livre_id', sa.Integer(), nullable=False),
    sa.Column('oeuvre_id', sa.Integer(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('pages', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['livre_id'], ['livres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['oeuvre_id'], ['oeuvre.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('livre_id', 'oeuvre_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livre_oeuvre')
    op.drop_table('livre_genre')
    op.drop_table('livre_auteur')
    op.drop_table('user_role')
    op.drop_table('oeuvre_auteur')
    op.drop_table('livres')
    op.drop_table('user')
    op.drop_table('serie')
    op.drop_table('role')
    op.drop_table('oeuvre')
    op.drop_table('langue')
    op.drop_table('genre')
    op.drop_table('emplacement')
    op.drop_table('editeur')
    op.drop_table('auteur')
    # ### end Alembic commands ###
